
a = int(input("Entre operand 1 : "))
b = int(input("Entre operand 2 : "))
print("----------------------")
print("Mathmatical Operations")
print("----------------------")
print("sum: ",a+b)
print("sub: ",a-b)
print("mult: ",a*b)
print("div: ",a/b)
print("Expon: ",a**b)
print("Floor: ",a//b)
print("Mod: ",a%b)
print("----------------------")
print("Bitwise Operations")
print("----------------------")
print("AND: ",a&b)
print("OR: ",a|b)
print("XOR: ",a^b)
print("NOT a: ",~a)
print("NOT b: ",~b)
print("ShiftLeft a: ",a<<1)
print("ShiftLeft b: ",b<<1)
print("ShiftRight a: ",a>>1)
print("ShiftRight b: ",b>>1)
print("----------------------")
print("Relational Operations")
print("----------------------")
print("Equal: ",a==b)
print("Bigger: ",a>b)
print("Smaller: ",a<b)
print("----------------------")